### ISSUE TITLE
Making screenshots on getting an achievement optional

### ISSUE THREAD

**Issue by MisakiCopperrose** [MarkusBordihn/advancements_tracker#1]
**Is your feature request related to a problem? Please describe.**
The screenshot on receiving an achievement seems to be causing issues with the nicephore mod: https://www.curseforge.com/minecraft/mc-mods/nicephore

It crashes the game when trying to create many new screenshots when loading a saved world/joining a server.

**Describe the solution you'd like**
I would likere there to be an option in the configs to turn off the screenshot on receiving an achievement feature.

**Describe alternatives you've considered**
Removing the nicephore mod from my game. However, im running the game on 4k and i can't send normal minecraft pngs on discord because of that XD.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report and the details.
The multiple screenshot issue is already fixed in version 0.1.6., but I added the option to disable the screenshot generation in version 0.2.0. The new version should be live in the next 30 min or so.
