### ISSUE TITLE
Advancements lost on dimension change & server/world rejoin

### ISSUE THREAD

**Issue by KinfThaDerp** [MarkusBordihn/advancements_tracker#2]
**Describe the bug**
Advancements are lost between changing dimension or rejoining servers & worlds

**To Reproduce**
1. Mark a(n) advancement(s) for it to show up in the advancement tracker
2. Change dimension (nether, end, or other)  OR  leave Server or world and join it again
3. Advancements tracked are gone

**Expected behavior**
Advancements tracked should remain, as marking them each time is just annoying and lessens the use of a "Tracker", since now you have to remember about the advancements instead of being reminded by the tracker.

**Comment by MarkusBordihn** [comment]
Thanks for the report. I currently working on implementing this to allow to store the tracked advancements per Server.
