### ISSUE TITLE
Advancement Tracker not removing completed advancements

### ISSUE THREAD

**Issue by jelaw21** [MarkusBordihn/advancements_tracker#6]
**Describe the bug**
When I track an advancement and complete it, the tracker doesn't remove it. However, if I relog, it removes them,. But then, after the first advancement completes, it disappears from the tracker, but then anymore newly completed advancements don't. I have a ton of custom advancements, along with 4 starter advancements in the config. 

1.16.5-0.2.1

**To Reproduce**
1. Create a Custom Advancement
2. Assign it to the Tracker
3. Complete it
4. It does not remove from tracker.

**Expected behavior**
I expected the Advancement to be removed from the tracker when its completed.

**Screenshots**
![advancement_tracking](https://user-images.githubusercontent.com/21100827/115100469-e0816d80-9f0a-11eb-8dd5-1a4c5a612af2.gif)

**Debugging**
I don't see any relevant in the logs.

**Comment by jelaw21** [comment]
If it helps, here are just a few of my custom advancements. Some may not work because of modded items, but this is primarily vanilla stuff.
[survival.zip](https://github.com/MarkusBordihn/advancements_tracker/files/6328577/survival.zip)

**Comment by jelaw21** [comment]
AH HA, figured it out. It was the screenshot feature messing it up. That's why only the first advancement succeeded. I am playing through Curseforge and my files are saved under Document/Curseforge/Minecraft/Instances. Maybe that could be causing the screenshot feature to hang up the program?

**Comment by jelaw21** [comment]
Nope, still doing weird things. Start a new world, advancement disappear when completed. Save and quit, log back in, advancements don't track.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report, I will try to reproduce the issue and will try to implement a fix.

**Comment by jelaw21** [comment]
Ok, I think I've narrowed it. This one was hard to nail down. If I don't add any preloaded advancements, the tracker doesn't update.  If I add preloaded advancement in default, the tracker will update only for those quests, and not any manually added to tracker. If I add preloaded advancements in local cache, everything appears to work great, manually loaded or not.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the additional details. I was able to reproduce the issue mostly in the single player mode and found some issues I need to address.
I need to rewrite some of the logic and will provide an updated version which will fix these issues in the next days.

**Comment by jelaw21** [comment]
Cool. Glad you found something cause I thought I was going nuts.

**Comment by MarkusBordihn** [comment]
Ok, this was more complex that I thought, because they advancements event handler are not 100% reliable.

I added several ways and checks to make sure advancements and update are not missed.
But please open a new issue request if you still seeing an issue with a specific setup or compination of mods.
